### PR TITLE
test(ObjectSummary): properly find virtualized tree element

### LINKED ISSUE #1861: Fix broken e2e tests
There is some issue with `ds_vslots` table

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1861

Because of some changes in our tests or ydb docker, some of the tables, that we used in tests, occurred in the bottom virtualized part of the `SchemaTree`. Previously our tests wasn't able to locate such elements.

I added `getTreeItem` method to `ObjectSummary` test class, this method can locate object not only in the visible part of `SchemaTree`.

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1863/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 262 | 260 | 0 | 2 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 80.05 MB | Main: 80.05 MB
  Diff: 0.00 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: tests/suites/tenant/summary/ObjectSummary.ts [hunk 1]
```diff
@@ -181,8 +195,49 @@ export class ObjectSummary {
...
 
+    async getTreeItem(text: string) {
+        await this.isTreeVisible();
+        await this.isTreeLoaded();
+
+        const itemLocator = this.treeRows.filter({hasText: text}).first();
+
+        if (await itemLocator.isVisible({timeout: 1000})) {
+            return itemLocator;
+        }
```
Comment (artemmufazalov) [inline tests/suites/tenant/summary/ObjectSummary.ts:206]: I didn't use default timeouts here because they are too big for such case. In this method we assume, that the tree is present and already loaded with `isTreeVisible` and `isTreeLoaded`. We spend little time to check elements, since in the worst scenario there will be 10 loops - with default timeout (`VISIBILITY_TIMEOUT`) it may be more than 100 seconds for one function call (in my version max is about 7 seconds)

File: tests/suites/tenant/summary/ObjectSummary.ts [hunk 2]
```diff
@@ -181,8 +195,49 @@ export class ObjectSummary {
...
+
+        // Element could be in not rendered (virtualized) part of the tree
+        // Such element cannot be found by playwright
+        // Scroll 200px * 10 from top to bottom to find element
+        await this.tree.hover();
+        await this.tree.evaluate((e) => {
+            e.scrollTo({top: 0, behavior: 'instant'});
+        });
```
Comment (artemmufazalov) [inline tests/suites/tenant/summary/ObjectSummary.ts:214]: Scroll to top in case tree was already scrolled down

File: tests/suites/tenant/summary/ObjectSummary.ts [hunk 3]
```diff
@@ -181,8 +195,61 @@ export class ObjectSummary {
...
 
+    async getTreeItem(text: string) {
+        // Ensure tree is ready for the search
+        await this.isTreeVisible();
+        await this.isTreeLoaded();
+
+        const itemLocator = this.treeRows.filter({hasText: text}).first();
+
+        // Default timeout is too big for such case
+        const timeout = 500;
```
Comment (artemmufazalov) [inline tests/suites/tenant/summary/ObjectSummary.ts:206]: I didn't use default timeouts here because they are too big for such case. In this method we assume, that the tree is present and already loaded with `isTreeVisible` and `isTreeLoaded`. We spend little time to check elements, since in the worst scenario there will be 10 loops - with default timeout (`VISIBILITY_TIMEOUT`) it may be more than 100 seconds for one function call (in my version max is about 7 seconds)

**Review by astandrik — APPROVED** [review]
