### PR TITLE
fix(TenantNavigation): fix radio button value

### LINKED ISSUE #965: Tenant selected tab isn't changed by actions
`Query | Diagnostics`

If you click on buttons, tab is changed together with buttons value. But if the tab is changed via some other actions, for example by selecting template in schema tree, or by clicking on query in `Top Queries`, buttons values isn't changed

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #965

### CODE REVIEW

File: src/containers/Tenant/TenantNavigation/TenantNavigation.tsx [hunk 1]
```diff
@@ -31,16 +34,14 @@ export const TenantNavigation = () => {
...
-
     return (
         <div className={b()}>
             <RadioButton
                 width="auto"
                 onUpdate={handleUpdate}
                 size="l"
                 className={b('body')}
-                defaultValue={getCurrentItem().id}
+                value={tenantPage}
```
Comment (Raubzeug) [inline src/containers/Tenant/TenantNavigation/TenantNavigation.tsx:44]: It seems that it will be enough just change property from `defaultValue` to `value`. 
Lets stick to this and return all tabs calculations to `useTenantNavigation`?

**Review by Raubzeug — CHANGES_REQUESTED** [review]

File: src/containers/Tenant/TenantNavigation/TenantNavigation.tsx (hunk 1 above)
Comment (artemmufazalov) [reply src/containers/Tenant/TenantNavigation/TenantNavigation.tsx:44]: I don't understand, why we need to set `current` property to `items` and get current item with `getCurrentItem`, if we could just use `tenantPage`. For me it just adds complexity
