### PR TITLE
fix: use blue color only for not replicated vdisks

### LINKED ISSUE #2081: Use `Green` for `Blue` vdisk `DiskSpace` and `FrontQueues` flags
If `DiskSpace` or `FrontQueues` are `Blue`, use `Green` flag instead for severity calculation (vdisk calculated status, used to colorize it in tables).

In places where we display these flags only, use `Blue` as before:

Image

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #2081 

### Test Status: <span style="color: green;">✅ PASSED</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2110/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 298 | 298 | 0 | 0 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 83.27 MB | Main: 83.27 MB
  Diff: +0.24 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/utils/disks/calculateVDiskSeverity.ts [hunk 1]
```diff
@@ -52,5 +52,10 @@ function getColorSeverity(color?: EFlag) {
         return NOT_AVAILABLE_SEVERITY;
     }
 
+    // Blue is reserved for not replicated VDisks
```
Comment (artemmufazalov) [inline src/utils/disks/calculateVDiskSeverity.ts:55]: `getColorSeverity` is used to convert `DiskSpace` and `FrontQueues` flags to severity

**Review by Raubzeug — CHANGES_REQUESTED** [review]
Lets add a test for this case

**Review by Raubzeug — APPROVED** [review]
