### PR TITLE
fix(FormattedBytes): show 1_000 with another unit

### LINKED ISSUE #1455: Hard to compare table's data size
I was comparing the size of the data in the two tables to see which of the two tables was larger. I found the information I needed in the `Info` tab of the table, under the `Table Stats` section. One table had `132 MB` and this was very clearly displayed, the other table displayed `78 213 KB`, which equates to about `78 MB`. I needed to do a calculation in my head to compare the sizes, couldn't do it with a quick glance.

First Table:
image

Second Table:
image

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1455 

Before:
Screenshot 2025-02-03 at 14 18 13

After:
Screenshot 2025-02-03 at 14 18 32

### Test Status: <span style="color: green;">✅ PASSED</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1901/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 262 | 262 | 0 | 0 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 80.19 MB | Main: 80.20 MB
  Diff: 2.37 KB (-0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/components/FormattedBytes/utils.tsx [hunk 1]
```diff
@@ -11,5 +11,5 @@ export const toFormattedSize = (
         return null;
     }
 
-    return <FormattedBytes value={value} significantDigits={2} {...params} />;
+    return <FormattedBytes value={value} {...params} />;
```
Comment (Raubzeug) [inline src/components/FormattedBytes/utils.tsx:14]: It seems we don't use `significantDigits` param any more. What do you think about remove it completely? It seems it will simplify logic for formatting values a lot.

**Review by Raubzeug — CHANGES_REQUESTED** [review]

File: src/utils/dataFormatters/__test__/formatNumbers.test.ts [hunk 2]
```diff
@@ -21,6 +21,12 @@ describe('formatNumericValues', () => {
         const result = formatNumericValues(1024, 2048);
         expect(result).toEqual(['1', `2${UNBREAKABLE_GAP}k`]);
     });
+
+    it('should format values without units (less than 1000)', () => {
+        const result1 = formatNumericValues(10, 20);
+        expect(result1).toEqual(['10', `20`]);
```
Comment (artemmufazalov) [inline src/utils/dataFormatters/__test__/formatNumbers.test.ts:27]: Before in such case `formatNumericValues` returned `['0', '0']`

**Review by Raubzeug — CHANGES_REQUESTED** [review]

File: src/utils/dataFormatters/formatNumber.ts [hunk 3]
```diff
@@ -25,43 +29,19 @@ const sizes = {
...
-
-    const thousandLevel = sizes.thousand.value * multiplier;
-    const millionLevel = sizes.million.value * multiplier;
-    const billionLevel = sizes.billion.value * multiplier;
-    const trillionLevel = sizes.trillion.value * multiplier;
-
-    let size: Digits = 'thousand';
-
-    if (value > thousandLevel) {
+export const getNumberSizeUnit = (value: number) => {
```
[the remark this answers is not in the document]
Comment (artemmufazalov) [reply src/utils/dataFormatters/formatNumber.ts:32]: We use custom getter, because together with auto formatting we can pass specific unit - it's helpful for data inside tables (data on every row should be with the same unit). AFAIK `numeral` cannot do formatting to specific units. While `formatNumber` is not widely used, `formatBytes` with the same approach is used in most of the tables

**Review by Raubzeug — APPROVED** [review]
