### PR TITLE
fix(UserSettings): show description under setting control

### LINKED ISSUE #974: Display settings description in the right side
We have description under the settings themselves:
Screenshot 2024-07-02 at 18 07 35

There is more space in the right side, so it could look better there:
image

### PR DESCRIPTION
**Pull request by Raubzeug**
closes #974
[Stand](http://ydb-vla-dev02-003.search.yandex.net:8765/monitoring/cluster/tenants?search=)

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1827/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 262 | 261 | 0 | 1 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 79.96 MB | Main: 79.96 MB
  Diff: +0.77 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/containers/UserSettings/UserSettings.tsx [hunk 1]
```diff
@@ -32,9 +33,17 @@ export const UserSettings = ({settings: userSettings}: UserSettingsProps) => {
...
-                                            <Settings.Item key={setting.title} {...setting}>
+                                            <Settings.Item
+                                                key={setting.title}
+                                                align="top"
+                                                {...rest}
+                                            >
                                                 <Setting {...setting} />
+                                                <Text color="secondary" as="div">
+                                                    {description}
+                                                </Text>
```
Comment (artemmufazalov) [inline src/containers/UserSettings/UserSettings.tsx:46]: A margin between setting control and text is needed

Screenshot 2025-01-16 at 17 39 27

**Review by artemmufazalov — CHANGES_REQUESTED** [review]

File: src/containers/UserSettings/UserSettings.tsx (hunk 1 above)
Comment (Raubzeug) [reply src/containers/UserSettings/UserSettings.tsx:46]: I'm not sure... I've looked at navigation stories, and there's no additional space between control and text:  https://preview.yandexcloud.dev/navigation/?path=/story/components-settings--showcase (see "Communication" tabl)

**Review by artemmufazalov — APPROVED** [review]
