### PR TITLE
fix(Node): wait for capabilities before tabs

### LINKED ISSUE #3305: Node page tabs works badly
Image

Image

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #3305 

Currently nodes tabs render before capabilities loaded, some tabs may appear, some other tabs may be hidden. Wait for capabilities and node data before showing content to ensure correct tabs list

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/3314/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 192 | 191 | 0 | 1 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 62.67 MB | Main: 62.67 MB
  Diff: +0.28 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/containers/Node/Node.tsx [hunk 1]
```diff
@@ -149,7 +155,7 @@ export function Node() {
             {<NodePageTitle node={node} />}
             {error ? <ResponseError error={error} className={b('error')} /> : null}
             {<NodePageInfo node={node} loading={pageLoading} />}
-            {nodeId ? (
+            {!pageLoading && nodeId ? (
```
Comment (Raubzeug) [inline src/containers/Node/Node.tsx]: May be only this change will be enough to achieve desired behavior?

**Review by Raubzeug — CHANGES_REQUESTED** [review]

File: src/containers/Node/Node.tsx (hunk 1 above)
Comment (artemmufazalov) [reply src/containers/Node/Node.tsx]: No. There is another issue: if tabs are filtered before data is loaded, sometimes it is not possible to get to the same tab after page reload.

For example:
1. I chose Threads or Storage tab, it is saved in url
2. I reload page
3. My tab is now Tablets, because tabs list was modified before data was loaded, there is no data for Threads or Storage tab initially

**Review by Raubzeug — APPROVED** [review]
