### PR TITLE
fix(ClusterInfo): update links view

### LINKED ISSUE #1741: Update cluster links
1. Cores -> Coredumps
2. Display in column (we need to discuss it)

Screenshot 2024-12-03 at 12 35 03

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1741

Updated cluster links view, it now looks like Tablet page

Screenshot 2024-12-10 at 16 27 38

Stand (these links are invalid, it's only to display): https://nda.ya.ru/t/O2N0YNcr7AJF5c

### Test Status: <span style="color: green;">✅ PASSED</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1746/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 208 | 208 | 0 | 0 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: 🔺
  Current: 65.87 MB | Main: 65.86 MB
  Diff: +0.01 MB (0.02%)

  ⚠️ Bundle size increased. Please review.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/containers/Cluster/ClusterInfo/utils.tsx [hunk 1]
```diff
@@ -80,7 +61,7 @@ export const getInfo = (
     if (dataCenters?.length) {
         info.push({
             label: i18n('label_dc'),
-            value: <Tags tags={dataCenters} gap={2} />,
+            value: <Tags tags={dataCenters} gap={2} className={b('dc')} />,
```
Comment (artemmufazalov) [inline src/containers/Cluster/ClusterInfo/utils.tsx:64]: Set element height, so info and links section rows have the same height

File: src/containers/Cluster/ClusterInfo/utils.tsx [hunk 2]
```diff
@@ -29,18 +26,6 @@ const COLORS_PRIORITY: Record<EFlag, number> = {
     Grey: 0,
 };
 
-export const compareTablets = (tablet1: TTabletStateInfo, tablet2: TTabletStateInfo) => {
```
Comment (artemmufazalov) [inline src/containers/Cluster/ClusterInfo/utils.tsx:32]: Unneeded function

File: src/containers/Cluster/ClusterInfo/ClusterInfo.scss [hunk 3]
```diff
@@ -3,38 +3,19 @@
...
     }
 
-    &__error {
-        @include mixins.body-2-typography();
+    &__section-title {
+        margin: var(--g-spacing-1) 0 var(--g-spacing-3);
+        @include mixins.text-subheader-2();
     }
 
-    &__metrics {
```
Comment (artemmufazalov) [inline src/containers/Cluster/ClusterInfo/ClusterInfo.scss:14]: I didn't find usages of these classes, so I deleted them

File: src/containers/Cluster/ClusterInfo/ClusterInfo.tsx [hunk 4]
```diff
@@ -29,24 +32,66 @@ export const ClusterInfo = ({
...
+    const renderInfo = () => {
         if (error && !cluster) {
             return null;
         }
 
-        return <InfoViewer dots={true} info={clusterInfo} />;
+        return (
+            <div>
+                <div className={b('section-title')}>{i18n('title_info')}</div>
+                <DefinitionList nameMaxWidth={200}>
```
Comment (artemmufazalov) [inline src/containers/Cluster/ClusterInfo/ClusterInfo.tsx:45]: 200 max width is names width of `InfoViewer`, it will look the same as `Tablet` page

File: src/containers/Cluster/ClusterInfo/ClusterInfo.tsx [hunk 5]
```diff
@@ -29,24 +32,66 @@ export const ClusterInfo = ({
...
+                                {value}
+                            </DefinitionList.Item>
+                        );
+                    })}
+                </DefinitionList>
+            </div>
+        );
+    };
+
+    const renderLinks = () => {
```
Comment (Raubzeug) [inline src/containers/Cluster/ClusterInfo/ClusterInfo.tsx:58]: `const linksList = links.concat(clusterLinks)` ?
And farther logic should become leaner.

**Review by Raubzeug — APPROVED** [review]

**Review by Raubzeug — APPROVED** [review]
