### PR TITLE
fix(Tenant): fix tabs reset on schema object change

### LINKED ISSUE #1880: "tablets" drops selection
in diagnostics mode selected tab "tablets" drops selection after clicking to another object in the schema tree

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1880 

Stand: https://nda.ya.ru/t/V1P0upfw7BXe2E

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1881/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 262 | 260 | 0 | 2 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 80.19 MB | Main: 80.19 MB
  Diff: +3.04 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/containers/Tenant/Tenant.tsx [hunk 1]
```diff
@@ -100,8 +101,18 @@ export function Tenant(props: TenantProps) {
...
+        selectSchemaObjectData(state, path, tenantName),
+    );
+
+    // Use preloaded data if there is no current item data yet
+    const currentPathType =
+        currentItem?.PathDescription?.Self?.PathType ??
+        preloadedData?.PathDescription?.Self?.PathType;
+    const currentPathSubType =
+        currentItem?.PathDescription?.Self?.PathSubType ??
+        preloadedData?.PathDescription?.Self?.PathSubType;
```
Comment (artemmufazalov) [inline src/containers/Tenant/Tenant.tsx:115]: Use type and sub type from object parent's `Children` field
