### PR TITLE
fix(ObjectSummary): do not display CreateTime if CreateStep is 0

### LINKED ISSUE #1886: do not display CreateTime if CreateStep is 0 or absent

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1886

Prevent `1970-01-01 03:00` in created time

Screenshot 2025-03-17 at 18 05 29

### Test Status: <span style="color: green;">✅ PASSED</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2018/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 264 | 263 | 0 | 0 | 1 |

  
  <details>
  <summary>Test Changes Summary ⏭️1 </summary>

  #### ⏭️ Skipped Tests (1)
1. Streaming query shows some results and banner when stop button is clicked (tenant/queryEditor/queryEditor.test.ts)

  </details>

  ### Bundle Size: ✅
  Current: 83.22 MB | Main: 83.22 MB
  Diff: +1.21 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/components/InfoViewer/formatters/common.ts [hunk 1]
```diff
@@ -1,12 +1,13 @@
...
+import {EMPTY_DATA_PLACEHOLDER} from '../../../utils/constants';
 import {formatDateTime} from '../../../utils/dataFormatters/dataFormatters';
 import i18n from '../i18n';
 import {createInfoFormatter} from '../utils';
 
 export const formatCommonItem = createInfoFormatter<TDirEntry>({
     values: {
         PathType: (value) => value?.substring('EPathType'.length),
-        CreateStep: formatDateTime,
+        CreateStep: (value) => (Number(value) ? formatDateTime(value) : EMPTY_DATA_PLACEHOLDER),
```
Comment (astandrik) [inline src/components/InfoViewer/formatters/common.ts:10]: maybe it would be better to handle zero values in formatDateTime and to pass EMPTY_DATA_PLACEHOLDER as defaultValue ?

Can't imagine anyone would need 1970-01-01 03:00 value (that is returned for formatDateTime(0)) anywhere accross the project

File: src/containers/Tenant/Info/ExternalTable/ExternalTable.tsx [hunk 2]
```diff
@@ -15,27 +15,30 @@ import './ExternalTable.scss';
...
-            label: i18n('external-objects.data-source'),
-            value: DataSourcePath && (
-                <span title={DataSourcePath}>
-                    <LinkWithIcon title={dataSourceName || ''} url={pathToDataSource} />
-                </span>
-            ),
-        },
     ];
+
+    if (Number(CreateStep)) {
```
Comment (astandrik) [inline src/containers/Tenant/Info/ExternalTable/ExternalTable.tsx:28]: Mb it would be more consistent to display EMPTY_DATA_PLACEHOLDER (via date formatter and defaultValue) everywhere?

Comment (artemmufazalov) [reply src/containers/Tenant/Info/ExternalTable/ExternalTable.tsx:28]: I don't think so. Normally, we have 0 `CreateStep` for certain list of entities - Domain, databases, system tables. So in your case there will be always placeholder there. I added placeholder in `formatCommonItem` just as fallback, but you are right - it's better to check correctness inside `formatDateTime`

**Review by astandrik — APPROVED** [review]
