### PR TITLE
fix(PDiskSpaceDistribution): update slots severity calculation

### LINKED ISSUE #1812: Update severity calculation for VDisks inside PDisk space distribution
1. Rename `Disk Distribution` to `Space Distribution`
2. Colorize Log inside distribution with 85/95 size thresholds
3. Update severity calculation for VDisks inside space distribution (`calculateVDiskSeverity` function)
3.1. Colorize VDisks inside distribution with 85/95 size thresholds
3.2. ~~Do not include PDisk status in VDisk severity calculation~~ there is not PDiskStatus in VDisk severity calculation
3.3. Do not change severity calculation inside Storage table

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1812

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1907/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 262 | 260 | 0 | 2 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 80.20 MB | Main: 80.19 MB
  Diff: +0.90 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/store/reducers/pdisk/utils.ts [hunk 1]
```diff
@@ -34,18 +35,20 @@ export function preparePDiskDataResponse([pdiskResponse = {}, nodeResponse]: [
...
+        const usagePercent = (Number(LogUsedSize) * 100) / Number(LogTotalSize);
+
         logSlot = {
             SlotType: 'log',
             Used: Number(LogUsedSize),
             Total: Number(LogTotalSize),
-            UsagePercent: (Number(LogUsedSize) * 100) / Number(LogTotalSize),
-            Severity: 1,
+            UsagePercent: usagePercent,
+            Severity: getSpaceSeverity(usagePercent),
```
Comment (artemmufazalov) [inline src/store/reducers/pdisk/utils.ts:51]: Colorize log just like other slots. For example, if log is 90/100, it should be yellow, if 99/100 - red.

File: src/store/reducers/pdisk/utils.ts [hunk 2]
```diff
@@ -60,11 +63,19 @@ export function preparePDiskDataResponse([pdiskResponse = {}, nodeResponse]: [
     preparedVDisks.sort((disk1, disk2) => Number(disk2.VDiskSlotId) - Number(disk1.VDiskSlotId));
 
     const vdisksSlots: SlotItem<'vDisk'>[] = preparedVDisks.map((preparedVDisk) => {
+        // VDisks do not have strict limits and can be bigger than they should
+        // In most storage views we don't colorize them depending on space usage
+        // Colorize them inside PDiskSpaceDistribution so overused slots will be visible
+        const slotSeverity = Math.max(
+            getSpaceSeverity(preparedVDisk.AllocatedPercent),
+            preparedVDisk.Severity || 0,
+        );
```
Comment (artemmufazalov) [inline src/store/reducers/pdisk/utils.ts:72]: We don't use allocated percent to get vdiks severity inside prepare functions, we use it only here while preparing slots

File: src/store/reducers/pdisk/utils.ts [hunk 3]
```diff
@@ -78,7 +89,7 @@ export function preparePDiskDataResponse([pdiskResponse = {}, nodeResponse]: [
     if (ExpectedSlotCount && ExpectedSlotCount > vdisksSlots.length) {
         const emptySlotsCount = ExpectedSlotCount - vdisksSlots.length;
 
-        let emptySlotSize = Number(EnforcedDynamicSlotSize);
+        let emptySlotSize = Number(SlotSize);
```
Comment (artemmufazalov) [inline src/store/reducers/pdisk/utils.ts:92]: There was a bug, added tests

File: src/utils/disks/calculatePDiskSeverity.ts [hunk 4]
```diff
@@ -17,13 +10,13 @@ export function calculatePDiskSeverity<
     },
 >(pDisk: T) {
     const stateSeverity = getStateSeverity(pDisk.State);
-    const spaceSeverityFlag = getUsageSeverityForPDisk(pDisk.AllocatedPercent || 0);
+    const spaceSeverity = getSpaceSeverity(pDisk.AllocatedPercent);
```
Comment (artemmufazalov) [inline src/utils/disks/calculatePDiskSeverity.ts:13]: Just little refactoring

**Review by Raubzeug — APPROVED** [review]
