### PR TITLE
fix: cpu and ram columns fallback

### LINKED ISSUE #2546: Unify behavior for CPU and RAM columns when no data is available
Currently, the behavior for the CPU and RAM columns is inconsistent when no data is available. As seen in the attached image, the RAM column displays "no data" when information is missing, but the CPU column shows a dash (–). To improve UX, make the behavior for the CPU column consistent with the RAM column (for example, display "no data" instead of a dash when CPU information is missing).

image1

### PR DESCRIPTION
**Pull request by Raubzeug**
closes #2546

<h2>Greptile Overview</h2>

<h3>Greptile Summary</h3>

This PR makes the CPU column behavior consistent with the RAM column by displaying "no data" when `PoolStats` is unavailable, instead of showing a dash.

**Key changes:**
- Removed early return that displayed placeholder when `PoolStats` was missing
- Added condition to only calculate pool-based CPU usage when `PoolStats` exists
- Disabled popover tooltip when `PoolStats` is unavailable
- Used optional chaining for `PoolStats?.map()` to safely handle undefined values
- The `ProgressViewer` component now properly displays "no data" when `totalPoolUsage` is `undefined`

<h3>Confidence Score: 5/5</h3>

- This PR is safe to merge with minimal risk
- The changes are minimal, focused, and correctly implement the desired behavior. The logic properly handles edge cases using optional chaining and conditional checks. The implementation is consistent with how the RAM column works.
- No files require special attention

<h3>Important Files Changed</h3>

File Analysis

| Filename | Score | Overview |
|----------|-------|----------|
| src/components/nodesColumns/columns.tsx | 5/5 | Changed CPU column to display "no data" placeholder when PoolStats is unavailable, consistent with RAM column behavior |

</details>

<h3>Sequence Diagram</h3>

```mermaid
sequenceDiagram
    participant Table as Nodes Table
    participant Column as getCpuColumn
    participant Cell as CellWithPopover
    participant Progress as ProgressViewer
    
    Table->>Column: render({row})
    
    alt CoresUsed and CoresTotal available
        Column->>Column: Calculate totalPoolUsage from cores
    else PoolStats available
        Column->>Column: Calculate totalPoolUsage from PoolStats
    else No data available
        Column->>Column: totalPoolUsage = undefined
    end
    
    Column->>Cell: Create CellWithPopover
    Cell->>Cell: Set disabled={!row.PoolStats}
    
    Column->>Progress: Pass totalPoolUsage
    
    alt totalPoolUsage is numeric
        Progress->>Table: Display progress bar
    else totalPoolUsage is undefined
        Progress->>Table: Display "no data"
    end
```

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/3211/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 378 | 375 | 0 | 1 | 2 |

  
  <details>
  <summary>Test Changes Summary ⏭️2 </summary>

  #### ⏭️ Skipped Tests (2)
1. Scroll to row, get shareable link, navigate to URL and verify row is scrolled into view (tenant/diagnostics/tabs/queries.test.ts)
2. Copy result button copies to clipboard (tenant/queryEditor/queryEditor.test.ts)

  </details>

  ### Bundle Size: ✅
  Current: 62.48 MB | Main: 62.48 MB
  Diff: 0.04 KB (-0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/components/nodesColumns/columns.tsx [hunk 1]
```diff
@@ -259,9 +255,10 @@ export function getCpuColumn<
                 <CellWithPopover
                     placement={['top', 'bottom']}
                     fullWidth
+                    disabled={!row.PoolStats}
                     content={
                         <DefinitionList responsive>
-                            {row.PoolStats.map((pool) =>
+                            {row.PoolStats?.map((pool) =>
```
Comment (astandrik) [inline src/components/nodesColumns/columns.tsx]: we check row.PoolStats in upper code - looks like ? is redundant

Comment (astandrik) [reply src/components/nodesColumns/columns.tsx]: mislooked - my bad

**Review by astandrik — APPROVED** [review]
