### PR TITLE
fix: replace native button titles with ActionTooltip

### LINKED ISSUE #905: Add title to all buttons
Check buttons and add titles if no.
For example, "restart tablet" action in Tablets tab in Diagnostics.

### PR DESCRIPTION
**Pull request by Arunkoo**
Fixes #905

What changed

Replaced native title tooltips on icon-only buttons with `ActionTooltip`.

Updated components:

- `Authentication` – show/hide password, close
- `TabletStorageInfo` / `GroupIdCell` – expand/collapse row
- `TableInfo` – partition config (gear)
- `EditorTabs` – new tab
-` OperationCell `– expand/collapse row
- `SavedQueries` – edit, delete
- Added matching `aria-label` for accessibility.

Notes

> Moved tooltip and aria-label strings to **i18n (added action.edit, reused existing keys)**. Fixed incorrect ./i18n import in SimplifiedPlan. Ensured no native title attributes remain on buttons. Controls with visible text were left unchanged.

<h3>Greptile Summary</h3>

This PR replaces native HTML `title` attributes on icon-only buttons with Gravity UI's `ActionTooltip` component across multiple components (`Authentication`, `TabletStorageInfo`, `TableInfo`, `EditorTabs`, `OperationCell`, `SavedQueries`, `YdbInternalUser`), adding matching `aria-label` attributes for accessibility. All tooltip strings are properly moved into component-local i18n keysets.

**Key changes:**
- `ActionTooltip` correctly applied to icon-only buttons with show/hide password, close, expand/collapse rows, manage partition config, new tab, edit, and delete actions.
- New i18n keys added in `Authentication/i18n/en.json`, `TabletStorageInfo/i18n/en.json`, `TableInfo/i18n/en.json`, and `Query/i18n/en.json`.
- All i18n keys are properly defined before use with action-appropriate phrasings.
- `TableGroup` button (which has visible text) correctly left unchanged without ActionTooltip.

**One minor efficiency concern:** In `Authentication.tsx`, the `closeButtonTitle` variable is computed unconditionally on every render but only used when the close button is rendered. Moving the i18n lookup into the conditional block would improve clarity.

<h3>Confidence Score: 4/5</h3>

- This PR is safe to merge — all changes are purely presentational tooltip upgrades with no logic changes or broken functionality.
- The PR correctly replaces native title attributes on icon-only buttons with ActionTooltip components and adds proper aria-labels. All i18n keys are correctly defined and used. The one point deduction reflects a minor efficiency concern in Authentication.tsx where closeButtonTitle is computed unconditionally despite only being used conditionally — this is a style/efficiency issue, not a functional bug.
- src/containers/Authentication/Authentication.tsx — minor efficiency improvement possible by moving closeButtonTitle i18n lookup into the conditional block

<h3>Important Files Changed</h3>

| Filename | Overview |
|----------|----------|
| src/containers/Authentication/Authentication.tsx | Show/hide password and close buttons correctly wrapped in ActionTooltip with proper i18n keys. Minor efficiency concern: closeButtonTitle is computed unconditionally despite only being used conditionally. |
| src/containers/Storage/TableGroup/TableGroup.tsx | Button with visible text content correctly left without ActionTooltip, following PR design intent for icon-only buttons only. |
| src/containers/Tenant/Query/QueryEditor/EditorTabs/EditorTabs.tsx | New tab button correctly wrapped in ActionTooltip using pre-existing i18n key 'editor-tabs.action.new-tab'. |
| src/containers/Tablet/components/TabletStorageInfo/columns.tsx | Expand/collapse buttons wrapped in ActionTooltip with i18n keys from local TabletStorageInfo keyset. |
| src/containers/Tenant/Diagnostics/Overview/TableInfo/TableInfo.tsx | Gear button wrapped in ActionTooltip with dedicated action key 'action_manage-partition-config', properly decoupled from section title key. |
| src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/OperationCell.tsx | Expand/collapse buttons wrapped in ActionTooltip with i18n keys imported from Query-level keyset; import resolves correctly. |
| src/containers/Tenant/Query/SavedQueries/SavedQueries.tsx | Edit and delete icon buttons wrapped in ActionTooltip with i18n-backed titles; delete reuses existing key appropriately. |
| src/containers/AsideNavigation/YdbInternalUser/YdbInternalUser.tsx | Login and logout icon-only buttons correctly wrapped in ActionTooltip with matching aria-labels. |

</details>

<h3>Flowchart</h3>

```mermaid
%%{init: {'theme': 'neutral'}}%%
flowchart TD
    A[Icon-only Button] -->|Before PR| B[native title attribute]
    A -->|After PR| C[ActionTooltip wrapper]
    C --> D[Button with aria-label]
    D --> E[Icon]

    C -->|title prop| F{i18n key source}
    F -->|Authentication| G["Authentication/i18n/en.json<br/>action_show-password<br/>action_hide-password<br/>action_close"]
    F -->|TabletStorageInfo| H["TabletStorageInfo/i18n/en.json<br/>action_expand / action_collapse"]
    F -->|TableInfo| I["TableInfo/i18n/en.json<br/>action_manage-partition-config"]
    F -->|Query components| J["Query/i18n/en.json<br/>action.edit / action.expand<br/>action.collapse<br/>editor-tabs.action.new-tab"]
    F -->|YdbInternalUser| K["AsideNavigation/i18n<br/>account.login / account.logout"]

    B -.->|Correctly unchanged| L["TableGroup: button has<br/>visible text"]
```

<sub>Last reviewed commit: 54a6600</sub>

> Greptile also left **1 inline comment** on this PR.

### CODE REVIEW

File: src/containers/Authentication/Authentication.tsx [hunk 1]
```diff
@@ -170,13 +170,26 @@ function Authentication({closable = false}: AuthenticationProps) {
                         onKeyDown={onEnterClick}
                         size="l"
                     />
-                    <Button
-                        onClick={onTogglePasswordVisibility}
-                        size="l"
-                        className={b('show-password-button')}
+                    <ActionTooltip
+                        title={
+                            showPassword
```
Comment (Raubzeug) [inline src/containers/Authentication/Authentication.tsx]: lets do title a variable and use it for both tooltip and aria
