### PR TITLE
fix(Authentication): handle login error properly

### LINKED ISSUE #1423: result of login operation ignored
if you login with any invalid user/password, login handler will return error, but UI ignores it.

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1423 

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1426/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 128 | 127 | 0 | 1 | 0 |

### Bundle Size: ✅
Current: 79.13 MB | Main: 79.13 MB
Diff: +0.08 KB (0.00%)

✅ Bundle size unchanged.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

### CODE REVIEW

File: src/containers/Authentication/Authentication.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ function Authentication({closable = false}: AuthenticationProps) {
     const history = useHistory();
     const location = useLocation();
 
-    const [authenticate, {error, isLoading}] = authenticationApi.useAuthenticateMutation(undefined);
+    const [authenticate, {isLoading}] = authenticationApi.useAuthenticateMutation(undefined);
```
Comment (astandrik) [inline src/containers/Authentication/Authentication.tsx:27]: Why didn't it work as expected?
I mean isn't auth mutation supposed to return error on error?

Comment (artemmufazalov) [reply src/containers/Authentication/Authentication.tsx:27]: Mutation result is always `{data, error}`, it cannot be processed by catch without `.unwrap()`. In previous version code in `.then` always ran, that caused the bug with error being ignored. I could use only `.then` as well - `.then(({data, error}) -> {})`, but  form with explicit `.catch` looks better for me

**Review by astandrik — APPROVED** [review]
