### PR TITLE
fix(VDiskPage): fix evict action

### LINKED ISSUE #1815: Cannot evict VDisk
Error: `Something went wrong, action cannot be completed`

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1815 

Issue for further improvements (tests): #1816

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1817/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 262 | 261 | 0 | 1 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 66.14 MB | Main: 66.14 MB
  Diff: +0.25 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/containers/VDiskPage/VDiskPage.tsx [hunk 1]
```diff
@@ -70,27 +71,31 @@ export function VDiskPage() {
 
     const handleEvictVDisk = async (isRetry?: boolean) => {
         if (vDiskIdParamsDefined) {
-            return (
-                newDiskApiAvailable ? window.api.vdisk.evictVDisk : window.api.tablets.evictVDiskOld
-            )({
```
Comment (artemmufazalov) [inline src/containers/VDiskPage/VDiskPage.tsx:75]: In such construction `this` is lost, so `this.post` inside functions doesn't work.

How it should be done in such case (adding `bind`):
```js
newDiskApiAvailable ? 
    window.api.vdisk.evictVDisk.bind(window.api.vdisk) :
    window.api.tablets.evictVDiskOld.bind(window.api.tablets)
```

**Review by astandrik — APPROVED** [review]
