### PR TITLE
fix: fields required in all groups and nodes requests

### LINKED ISSUE #1485: Request only needed fields in all storage and nodes requests (`fields_required` param)

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1485 

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1515/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 134 | 133 | 0 | 1 | 0 |

### Bundle Size: ✅
Current: 79.04 MB | Main: 79.03 MB
Diff: +0.00 MB (0.00%)

✅ Bundle size unchanged.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

### CODE REVIEW

File: src/utils/tableUtils/getRequiredDataFields.ts [hunk 1]
```diff
@@ -11,5 +11,5 @@ export function getRequiredDataFields<ColumnId extends string, RequiredField ext
         return fields;
     }, new Set<RequiredField>());
 
-    return Array.from(requiredFieldsSet);
+    return Array.from(requiredFieldsSet).sort();
```
Comment (artemmufazalov) [inline src/utils/tableUtils/getRequiredDataFields.ts:14]: Sort to ensure no additional requests when order changes.

Example:
Columns `[DiskSpace, Read]`, data fields `[State, Read]`
Columns `[Read, State]`, data fields `[Read, State]`

Although it's the same data, it will be requested twice, because of different state keys (`"fieldsRequired:State,Read"` vs `"fieldsRequired:Read,State"`

File: src/containers/StorageGroupPage/StorageGroupPage.tsx [hunk 2]
```diff
@@ -40,7 +40,9 @@ export function StorageGroupPage() {
     const shouldUseGroupsHandler = useStorageGroupsHandlerAvailable();
     const capabilitiesLoaded = useCapabilitiesLoaded();
     const groupQuery = storageApi.useGetStorageGroupsInfoQuery(
-        valueIsDefined(groupId) ? {groupId, shouldUseGroupsHandler, with: 'all'} : skipToken,
+        valueIsDefined(groupId)
+            ? {groupId, shouldUseGroupsHandler, with: 'all', fieldsRequired: 'all'}
```
Comment (artemmufazalov) [inline src/containers/StorageGroupPage/StorageGroupPage.tsx:44]: Only 1 group is requested here and we need all its data

File: src/containers/Storage/Storage.tsx [hunk 3]
```diff
@@ -107,6 +107,7 @@ export const Storage = ({database, viewContext, nodeId, groupId, pDiskId}: Stora
             groupId,
             pDiskId,
             shouldUseGroupsHandler: groupsHandlerAvailable,
+            fieldsRequired: 'all',
```
Comment (artemmufazalov) [inline src/containers/Storage/Storage.tsx:110]: It's possible to request data based on columns for not paginated storage. However, there is a problem: when you update columns, needed data fields are updated and data reloaded. For paginated table it isn't the issue, because we load only 50 entities, but for not paginated tables requests takes to long to load, so we need to avoid data reloads if possible

**Review by Raubzeug — APPROVED** [review]
