### PR TITLE
fix(Query): parse 200 error response

### LINKED ISSUE #860: Display errors for `viewer/query` requests with error in body with statusCode 200

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #860 

Test stand: https://nda.ya.ru/t/W3ooFk1b76HWU5

### CODE REVIEW

File: src/containers/Tenant/Diagnostics/TopQueries/TopQueries.tsx [hunk 1]
```diff
@@ -91,8 +91,8 @@ export const TopQueries = ({path, type}: TopQueriesProps) => {
     };
 
     const renderContent = () => {
-        if (error && typeof error === 'object' && !(error as any).isCancelled) {
```
Comment (artemmufazalov) [inline src/containers/Tenant/Diagnostics/TopQueries/TopQueries.tsx:94]: With rtk query requests are not cancelled as they were previously

File: src/store/reducers/explainQuery/explainQuery.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+import {api} from '../api';
+
+import type {PreparedExplainResponse} from './types';
+import {prepareExplainResponse} from './utils';
+
+interface ExplainQueryParams extends QueryRequestParams {
+    mode?: QueryMode;
+}
+
+export const explainQueryApi = api.injectEndpoints({
```
Comment (artemmufazalov) [inline src/store/reducers/explainQuery/explainQuery.ts:13]: I removed `getExplainAst` request, since we don't request it separately now

**Review by Raubzeug — APPROVED** [review]
