### PR TITLE
fix(PaginatedStorage): properly pass ids, display 1 node on Node page

### LINKED ISSUE #1380: Fix `nodeId` and `groupId` filters in `PaginatedStorage`
Currently, these params are not properly passed to the request. As a result such Storage doesn't work well on Node page

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1380 

If `PaginatedStorage` enabled, Storage tab on Node page show cluster nodes, while it should show only one node

### Test Status: <span style="color: green;">✅ PASSED</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1382/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 124 | 124 | 0 | 0 | 0 |

### Bundle Size: ✅
Current: 79.13 MB | Main: 79.13 MB
Diff: +0.00 MB (0.00%)

✅ Bundle size unchanged.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

### CODE REVIEW

File: src/containers/Storage/Storage.tsx [hunk 1]
```diff
@@ -90,8 +89,7 @@ export const Storage = ({database, nodeId, groupId, pDiskId}: StorageProps) => {
             database,
             with: visibleEntities,
             node_id: nodeId,
-            // node_id and group_id params don't work together
-            group_id: valueIsDefined(nodeId) ? undefined : groupId,
```
Comment (artemmufazalov) [inline src/containers/Storage/Storage.tsx:94]: Was fixed on backend recently

File: src/containers/Storage/PaginatedStorageNodes.tsx [hunk 2]
```diff
@@ -111,8 +117,7 @@ function GroupedStorageNodesComponent({database, groupId, nodeId}: PaginatedStor
             with: 'all',
             filter: searchValue,
             node_id: nodeId,
-            // node_id and group_id params don't work together
-            group_id: valueIsDefined(nodeId) ? undefined : groupId,
```
Comment (artemmufazalov) [inline src/containers/Storage/PaginatedStorageNodes.tsx:115]: It was fixed on backend recently

**Review by Raubzeug — APPROVED** [review]
