### PR TITLE
fix!: use uiFactory for logs and monitoring links

### LINKED ISSUE #2136: Use `uiFactory` for external props
Following function should be added to factory and removed from props:
`getLogsLink`
`getMonitoringLink`
`getMonitoringClusterLink`

Reason
- it's much easier to use it in place, than to drill it through several components as props
- it will be better, if we use the same approach for external functions

It's needed to release it at least as minor (they are changes to external api), it is needed to support changes in UI versions, that use embedded ui as a package

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #2136 

PR to merge these changes with current major.

Goals:
1) Allow further refactoring of additional props - prevent props drilling, use funcs in place
2) Single API for external options, function and configs

Usage when ui as a package:
```
const {store, history} = configureStore();

configureUIFactory({
    onCreateDB: getCreateDBDialog,
    onDeleteDB: getDeleteDBDialog,

    getLogsLink: getLogsLink,
    getMonitoringLink: getMonitoringLinkExtended,
    getMonitoringClusterLink: getMonitoringClusterLinkExtended,
});

componentsRegistry
    .set('StaffCard', StaffCard)
    .set('AsideNavigation', AsideNavigationInternal)
    .set('ShardsTable', ShardsTable);

function render() {
    const container = document.getElementById('root');
    if (!container) {
        throw new Error("Can't find root element");
    }

    const root = ReactDOM.createRoot(container);

    root.render(
        <ErrorBoundary>
            <App store={store} history={history} userSettings={internalSettings} />
        </ErrorBoundary>,
    );
}
```

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2274/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 318 | 317 | 0 | 1 | 0 |

  😟 No changes in tests. 😕

  ### Bundle Size: ✅
  Current: 83.47 MB | Main: 83.47 MB
  Diff: +0.33 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/containers/AppWithClusters/AppWithClusters.tsx [hunk 1]
```diff
@@ -18,32 +13,21 @@ import {ExtendedTenant} from './ExtendedTenant/ExtendedTenant';
...
         <App store={store} history={history} userSettings={userSettings}>
             <AppSlots.ClusterSlot>
                 {({component}) => {
                     return (
                         <ExtendedCluster
                             component={component}
-                            getLogsLink={getLogsLink}
-                            getMonitoringLink={getMonitoringLink}
-                            getMonitoringClusterLink={getMonitoringClusterLink}
+                            getLogsLink={uiFactory.getLogsLink}
```
Comment (artemmufazalov) [inline src/containers/AppWithClusters/AppWithClusters.tsx:28]: I didn't refactored additional props themselves, it's could be done further, these changes are to merge with current major and to not do another

**Review by Raubzeug — APPROVED** [review]
