### PR TITLE
fix(VDiskPage): use vdisk_id for api requests if possible

### LINKED ISSUE #3000: VDisk page - Tablets table not working
For now pDiskId is not passing with query params, so tablets table is broken.

### PR DESCRIPTION
**Pull request by Raubzeug**
closes #3000
[Stand](https://nda.ya.ru/t/cA9AA6MN7Lnjjq)

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
  📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/3001/)

  | Total | Passed | Failed | Flaky | Skipped |
  |:-----:|:------:|:------:|:-----:|:-------:|
  | 378 | 374 | 0 | 2 | 2 |

  
  <details>
  <summary>Test Changes Summary ⏭️2 </summary>

  #### ⏭️ Skipped Tests (2)
1. Scroll to row, get shareable link, navigate to URL and verify row is scrolled into view (tenant/diagnostics/tabs/queries.test.ts)
2. Copy result button copies to clipboard (tenant/queryEditor/queryEditor.test.ts)

  </details>

  ### Bundle Size: ✅
  Current: 45.87 MB | Main: 45.87 MB
  Diff: +0.90 KB (0.00%)

  ✅ Bundle size unchanged.

  <details>
  <summary>ℹ️ CI Information</summary>

  - Test recordings for failed tests are available in the full report.
  - Bundle size is measured for the entire 'dist' directory.
  - 📊 indicates links to detailed reports.
  - 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
  </details>

### CODE REVIEW

File: src/utils/disks/helpers.ts [hunk 1]
```diff
@@ -47,10 +48,10 @@ export function getPDiskId({
     return undefined;
 }
 
-export function getVDiskSlotBasedId(
-    nodeId: string | number,
-    pDiskId: string | number,
-    vDiskSlotId: string | number,
-) {
-    return [nodeId, pDiskId, vDiskSlotId].join('-');
+export function getVDiskSlotBasedId(params: VDiskBlobIndexStatParams) {
```
Comment (artemmufazalov) [inline src/utils/disks/helpers.ts]: I'd rename it to something else. Maybe just `getVDiskId`, vdisk id and slot id are different:

Id: "GroupID - GroupGeneration - Ring - Domain - VDisk"
Slot id: "NodeId - PDiskId - VDiskSlotId"

**Review by artemmufazalov — APPROVED** [review]
