### PR TITLE
fix: use both BSC and Whiteboard for disks

### LINKED ISSUE #1428: wrongfully report tooltips on non-existing disks
image

### LINKED ISSUE #1429: no tooltip on non-existing pdisk
image

### LINKED ISSUE #1457: [storage/groups]: use BSC data by default, use Whiteboard data only for missing fields
BSC data - data from entity, not from entity Whiteboard field

Backend returns BSC data and uses Whiteboard data as fallback.

Some fields are present only in Whiteboard, they should be taken from it.

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1457, closes #1428, closes #1429

UI should work as before, PR covers cases of DC shutdown

Stand: https://nda.ya.ru/t/dvb-Acis79L6xg

### Test Status: <span style="color: red;">❌ FAILED</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1564/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 134 | 129 | 2 | 3 | 0 |

### Bundle Size: 🔺
Current: 79.21 MB | Main: 79.20 MB
Diff: +0.01 MB (0.01%)

⚠️ Bundle size increased. Please review.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

### CODE REVIEW

File: src/utils/disks/calculateVDiskSeverity.ts [hunk 1]
```diff
@@ -1,18 +1,20 @@
...
     DISK_COLOR_STATE_TO_NUMERIC_SEVERITY,
     NOT_AVAILABLE_SEVERITY,
     VDISK_STATE_SEVERITY,
 } from './constants';
-import {isFullVDiskData} from './helpers';
-
-export function calculateVDiskSeverity(vDisk: TVDiskStateInfo) {
-    if (!isFullVDiskData(vDisk)) {
-        return NOT_AVAILABLE_SEVERITY;
-    }
```
Comment (artemmufazalov) [inline src/utils/disks/calculateVDiskSeverity.ts:14]: It doesn't needed, in this case function will return `NOT_AVAILABLE_SEVERITY` because disk lacks `VDiskState`

File: src/store/reducers/node/selectors.ts [hunk 2]
```diff
@@ -29,14 +29,13 @@ export const selectNodeStructure = createSelector(
             const groups = pool.Groups;
             groups?.forEach((group) => {
                 const vDisks = group.VDisks?.filter((el) => el.NodeId === nodeId).map(
-                    prepareVDiskData,
+                    prepareWhiteboardVDiskData,
```
Comment (astandrik) [inline src/store/reducers/node/selectors.ts:32]: why do we use only whiteboard data here (without bsc) ?

File: src/store/reducers/storage/utils.ts [hunk 3]
```diff
@@ -192,13 +196,13 @@ const prepareStorageNodeData = (node: TNodeInfo): PreparedStorageNode => {
 
     const pDisks = node.PDisks?.map((pDisk) => {
         return {
-            ...preparePDiskData(pDisk),
+            ...prepareWhiteboardPDiskData(pDisk),
```
Comment (astandrik) [inline src/store/reducers/storage/utils.ts:199]: Why do we use only whiteboard data and don't use bsc data here?

File: src/utils/disks/prepareDisks.ts [hunk 4]
```diff
@@ -1,70 +1,155 @@
...
-        ? preparePDiskData({
-              ...vdiskState.PDisk,
-              NodeId: vdiskState.PDisk.NodeId ?? vdiskState.NodeId,
-          })
+    const preparedPDisk = PDisk
+        ? prepareWhiteboardPDiskData({...PDisk, NodeId: PDisk?.NodeId ?? NodeId})
         : undefined;
 
-    const PDiskId = vdiskState.PDiskId ?? PDisk?.PDiskId;
+    const actualPDiskId = PDiskId ?? PDisk?.PDiskId;
```
Comment (astandrik) [inline src/utils/disks/prepareDisks.ts:48]: I would expect that preparedPDisk contains actial Id

File: src/utils/disks/prepareDisks.ts [hunk 5]
```diff
@@ -1,70 +1,155 @@
...
+    });
+
+    const Severity = calculateVDiskSeverity(vDiskState);
+
+    const StringifiedId = stringifyVdiskId(VDiskId);
 
-    const Donors = vdiskState.Donors?.map((donor) => {
-        return prepareVDiskData({...donor, DonorMode: true});
+    const preparedDonors = Donors?.map((donor) => {
+        return prepareWhiteboardVDiskData({...donor, DonorMode: true});
```
Comment (astandrik) [inline src/utils/disks/prepareDisks.ts:60]: Why do we use only whiteboard data here?

**Review by astandrik — CHANGES_REQUESTED** [review]

File: src/store/reducers/storage/utils.ts (hunk 3 above)
Comment (artemmufazalov) [reply src/store/reducers/storage/utils.ts:199]: In `prepareStorageNodeData` we prepare data that is received from `viewer/nodes`, it has only whiteboard data (`TPDiskStateInfo `)

File: src/utils/disks/prepareDisks.ts (hunk 4 above)
Comment (artemmufazalov) [reply src/utils/disks/prepareDisks.ts:48]: There might be no PDisk inside VDisk in some cases. For example, for `viewer/nodes` endpoint `VDisks` and `PDisks` are located in separate fields

File: src/utils/disks/prepareDisks.ts (hunk 5 above)
Comment (artemmufazalov) [reply src/utils/disks/prepareDisks.ts:60]: `prepareWhiteboardVDiskData` is used to prepare `TVDiskStateInfo`, donors inside `TVDiskStateInfo` have `TVDiskStateInfo` type, so the same function is used.

The same is for `storage/groups` response, vdisks there have type `TStorageVDisk`, donors have type `TStorageVDisk` as well, the same `prepareGroupsVDisk` function is used for both vdisk and its donors

**Review by astandrik — APPROVED** [review]
