### PR TITLE
fix: pass database to capabilities query

### LINKED ISSUE #1526: if the database name is known call compatibilities handler with it
otherwise we make decisions on other hosts versions

### PR DESCRIPTION
**Pull request by artemmufazalov**
Closes #1526

`/viewer/capabilities` is used on several pages and in different components. In order not to pass `database` param every time to hook, I made hook to take `database` param from search query by itself. To make it possible I named param the same way on every page where it's used

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1551/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 134 | 133 | 0 | 1 | 0 |

### Bundle Size: 🔺
Current: 79.11 MB | Main: 79.11 MB
Diff: +0.01 MB (0.01%)

⚠️ Bundle size increased. Please review.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

### CODE REVIEW

File: src/store/reducers/capabilities/hooks.ts [hunk 1]
```diff
@@ -1,16 +1,30 @@
...
 import type {Capability} from '../../../types/api/capabilities';
 import {useTypedSelector} from '../../../utils/hooks';
 
 import {capabilitiesApi, selectCapabilityVersion} from './capabilities';
 
+export function useCapabilitiesQuery() {
+    const [database] = useQueryParam('database', StringParam);
+
+    return capabilitiesApi.useGetClusterCapabilitiesQuery({
+        database: database ?? undefined,
```
Comment (artemmufazalov) [inline src/store/reducers/capabilities/hooks.ts:12]: `database ?? undefined` is used to get rid of `null` in type

File: src/components/TabletsStatistic/TabletsStatistic.tsx [hunk 2]
```diff
@@ -26,35 +25,18 @@ const prepareTablets = (tablets: TTabletStateInfo[]) => {
 
 interface TabletsStatisticProps {
     tablets: TTabletStateInfo[];
-    tenantName: string | undefined;
+    database: string | undefined;
     nodeId: string | number;
-    backend?: string;
```
Comment (artemmufazalov) [inline src/components/TabletsStatistic/TabletsStatistic.tsx:31]: `backend` is never passed here now, so I deleted it

**Review by Raubzeug — APPROVED** [review]
